### ISSUE TITLE
Map previous item ids/names to new item ids/names in WE

### ISSUE THREAD

**Issue by ds58** [Ruinscraft/mcplots-issues#21]

**Comment by Grant-drew** [comment]
```grass minecraft:grass_block
gold minecraft:gold_block
iron minecraft:iron_block
diamond minecraft:diamond_block
emerald minecraft:emerald_block
```

**Comment by ds58** [comment]
It is likely all that needs to be done is add the mappings here:

https://github.com/EngineHub/WorldEdit/blob/master/worldedit-core/src/main/resources/com/sk89q/worldedit/world/registry/legacy.json

**Comment by ds58** [comment]
I have decided to not do this
