### ISSUE TITLE
All The Plots Getting Greifed

### ISSUE THREAD

**Issue by TailsP** [Ruinscraft/mcplots-issues#22]
Plots Get Griefed For No Reason and get ruined For me I worked on my ploy for 3+ years and its all got ruined and I will literally gonna suicide if it won't get fixed because that's was my life project...

**Comment by ds58** [comment]
I don't believe this is a 1.13 related issue. If your plot was griefed, that is something you should inform staff about or rollback your self with the `//rollback` command.

Please make sure you trust whoever you add to your plot!

There is an issue on 1.13 however, where the `//rollback` command only logs worldedit changed blocks, not manually placed or broken blocks. See #3

**Comment by TailsP** [comment]
I know... I cant check who did it cause all the stuff doesn't care about this issue and.... that happened to other people tho.... maybe that's a hack ya know I saw 3 hackers when this happened...

**Comment by drewdorris** [comment]
Issue resolved anyway (the cause was #3)
